export MGLS_LICENSE_FILE="/var/mentor/mgls/licenses/authcodes.txt"
export TANNER_PATH="/var/mentor/Tanner/tanner"
export PATH="${PATH}:/var/mentor/Tanner/tanner/bin"
export OASYS_HOME="/var/mentor/oasys/Oasys-RTL-2022.1.R1"
export NITRO_HOME="/var/mentor/nitro/nitroPack-2020.2.R1/nitro"
